#!/usr/bin/perl

use strict;
use warnings;

use lib 'lib';

use 5.010001;
use Getopt::Long 2.38 ();
use App::Ack::ConfigLoader ();

use Data::Dumper;
local $Data::Dumper::Sortkeys = 1;


say 'Before processing, @ARGV is:';
say for @ARGV;

App::Ack::ConfigLoader::_check_for_mutually_exclusive_options();

say 'After processing, @ARGV is:';
say for @ARGV;

exit 0;
